workspace:
  base: /
  path: .
pipeline:
  init:
    image: 'containers.ssii.com/base/nodejs:lts-alpine'
    commands:
      - 'yarn install --network-concurrency 1'
    when:
      event: [push, tag, deployment]
      branch: [master, dev, testing, staging]
  build:
    image: 'containers.ssii.com/base/nodejs:lts-alpine'
    environment:
      - TZ=Asia/Shanghai
    secrets:
      - key1
      - key3
    commands:
      - 'yarn run build'
    when:
      event: [push, tag, deployment]
      branch: [master, dev, testing, staging]
# services:
#   database:
#     image: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=test